### ISSUE TITLE
makehuman-9999.ebuild builds for python 3.7

### ISSUE THREAD

**Issue by impiusnex** [brothermechanic/cg#37]
build completes just fine. Use flags are set to use python3.6
Running application gives this error;
```
$ makehuman
MakeHuman Copyright (C) 2001-2018 http://www.makehumancommunity.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. For details use the option --license

Initialized logging
VERSION: UNKNOWN:UNKNOWN
SHORT VERSION: alpha4
LONG VERSION: 1.2.0 Alpha4 (UNKNOWN:UNKNOWN)
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: No
DEFAULT ENCODING: utf-8
FILESYSTEM ENCODING: utf-8
STDOUT ENCODING: UTF-8
LOCALE PREFERRED ENCODING: UTF-8
WORKING DIRECTORY: /usr/share/makehuman
HOME LOCATION: /home/impiusnex/Documents
PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/usr/share/makehuman:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/lib/python3.7/site-packages
DLL PATH: /usr/lib/llvm/8/bin:/usr/lib/llvm/7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/nvidia-cg-toolkit/bin
SYS.VERSION: 3.7.4 (default, Oct  8 2019, 14:02:56)  [GCC 8.3.0]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /usr/lib/python-exec/python3.7/python3
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
PLATFORM.UNAME.RELEASE: 4.19.72-gentoo
PLATFORM.LINUX_DISTRIBUTION: Gentoo Base System 2.6
NUMPY.VERSION: 1.14.5
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Traceback (most recent call last):
  File "makehuman.py", line 613, in <module>
    main()
  File "makehuman.py", line 603, in main
    from mhmain import MHApplication
  File "./core/mhmain.py", line 45, in <module>
    import mh
  File "./lib/mh.py", line 50, in <module>
    from qtui import Keys, Buttons, Modifiers, Application
  File "./lib/qtui.py", line 45, in <module>
    from PyQt5 import QtCore, QtGui, QtOpenGL, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'
```
I've set python 3.6 via use flags;
media-gfx/makehuman python_targets_python3_6 python_single_targets_python3_6

but for some reason it tries to use python 3.7

**Comment by brothermechanic** [comment]
Hello
On my system i have only python-3.7* as python3
Try to remove all versions exept 3.7*

**Comment by brothermechanic** [comment]
Hello
Have you susses solution?
